website/views.py
from typing import Text
from flask import Blueprint, render_template, request, redirect, url_for, g
from flask_login import current_user
import flask_login
from flask_wtf import file
from werkzeug.utils import secure_filename
from website.models import Event , Review
from . import db
import os
from website.forms import Create, ReviewForm, Edit
from .models import *
import datetime

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    FirstEvent = Event.query.first()
    Carosels = Event.query.filter(Event.id.between(2, 4))
    Events = Event.query.all()
    current = datetime.datetime.now()    
    # testing template variable input
    # 1: brunch, 2: bordeaux, 3: graze, 4: dim sum, 5: donut, 6: senses, 7: beer, 8: book, 9: massimo

    return render_template('index.html',
    events=Events,
    carosels=Carosels, current = current, First = FirstEvent)

@bp.route('/upcoming')
def upcoming():
    FirstEvent = Event.query.first()
    Carosels = Event.query.filter(Event.id.between(2, 4))
    current = datetime.datetime.now()
    Events = Event.query.filter(Event.start_date >= current)     
    # testing template variable input
    # 1: brunch, 2: bordeaux, 3: graze, 4: dim sum, 5: donut, 6: senses, 7: beer, 8: book, 9: massimo

    return render_template('index.html',
    events=Events,
    carosels=Carosels, current = current, First = FirstEvent)

@bp.route('/passed')
def passed():
    FirstEvent = Event.query.first()
    Carosels = Event.query.filter(Event.id.between(2, 4))
    current = datetime.datetime.now()
    Events = Event.query.filter(Event.start_date <= current, Event.end_date >= current)     
    # testing template variable input
    # 1: brunch, 2: bordeaux, 3: graze, 4: dim sum, 5: donut, 6: senses, 7: beer, 8: book, 9: massimo

    return render_template('index.html',
    events=Events,
    carosels=Carosels, current = current, First = FirstEvent)

@bp.route('/week')
def week():
    FirstEvent = Event.query.first()
    Carosels = Event.query.filter(Event.id.between(2, 4))
    current = datetime.datetime.now()
    nextweek = current + datetime.timedelta(days=7)
    Events = Event.query.filter(Event.start_date.between(current, nextweek))    
    # testing template variable input
    # 1: brunch, 2: bordeaux, 3: graze, 4: dim sum, 5: donut, 6: senses, 7: beer, 8: book, 9: massimo

    return render_template('index.html',
    events=Events,
    carosels=Carosels, current = current, First = FirstEvent)

@bp.route('/create-event', methods = ['GET', 'POST'])
def create():
    createForm = Create()
    if createForm.validate_on_submit():
        #call the function that checks and returns image
        file_path=check_upload_file(createForm)
        event = Event(name = createForm.name.data,organiser = createForm.organiser.data,
        description = createForm.description.data, type = createForm.type.data,
        street = createForm.street.data, city = createForm.city.data, state = createForm.state.data,
        postcode = createForm.postcode.data, image = file_path, start_date = createForm.start_date.data,
        end_date = createForm.end_date.data, long_description = createForm.long_description.data, 
        ticket_price = createForm.ticket_price.data, user_id = current_user.id )
        # add the object to the db session
        db.session.add(event)
        # commit to the database
        db.session.commit()
        #Always end with redirect when form is valid
        print("YES")
        return redirect(url_for('main.index'))
    print("no")
    return render_template('create.html', form = createForm)

def check_upload_file(form):
  #get file data from form  
  fp=form.image.data
  filename=fp.filename
  #get the current path of the module file… store image file relative to this path  
  BASE_PATH=os.path.dirname(__file__)
  #upload file location – directory of this file/static/image
  upload_path=os.path.join(BASE_PATH,'static/img',secure_filename(filename))
  #store relative path in DB as image location in HTML is relative
  db_upload_path='/static/img/' + secure_filename(filename)
  #save the file and return the db upload path  
  fp.save(upload_path)
  return db_upload_path

@bp.route('/event-details<id>', methods = ['GET', 'POST'])
def details(id):
    form = ReviewForm()
    if form.validate_on_submit():
        review = Review(text = form.Text.data, event_id = id, user_id = current_user.id, user_name = current_user.name)
        db.session.add(review)
        db.session.commit()
    event = Event.query.filter_by(id=id).first()
    Reviews = Review.query.filter_by(event_id = id).all()
    # seed data - will replace with database queries (also needs formatting)
    
    # id, created_at, event_name, event_summary, event_description, event_date, event_time, event_price,
    # event_address, event_map, event_status, resale_platform, event_image, terms_and_conditions, ticket_type
    events = [event.id, event.start_date, event.name, event.description,event.long_description, 
    event.start_date, event.end_date, "$"+str(event.ticket_price), event.street + ","+ event.city + ","+event.state + ","+event.postcode ,
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.334032852493!2d153.03272421481861!3d-27.458858322815416!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b9159f3a25b26d5%3A0x1a8780632f1fcaa5!2sCloudland!5e0!3m2!1sen!2sau!4v1633571197297!5m2!1sen!2sau',
    'Upcoming', '''If you missed out on a ticket, or can no longer make the event, head to Tixel for 
    safe resale. Tixel is the only place where you can buy and sell guaranteed, genuine tickets. 
    Buy, sell or join the waitlist here.''', event.image, 
    '''Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the 
    industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and 
    scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
    into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the 
    release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
    software like Aldus PageMaker including versions of Lorem Ipsum.''', 'General Admission']


    # id, name, email, mobile

    return render_template('event_details.html',
    heading = "Event Details",
    events = events,
    Reviews = Reviews, form = form)



@bp.route('/booking-history')
def history():
    books = db.session.query(Booked_Event).filter_by(user_id = current_user.id).all()
    event_ids = []
    for book in books:
        event_ids.append(book.event_id)
    events = db.session.query(Event).filter(Event.id.in_(event_ids)).all()
    return render_template('booking_history.html',events = events )

@bp.route('/book<id>')
def book(id):
    book = db.session.query(Booked_Event).filter_by(user_id = current_user.id, event_id = id).first()
    if book:
        return redirect(url_for('main.index'))
    else:
        booked = Booked_Event(event_id = id, user_id = current_user.id)
        db.session.add(booked)
        db.session.commit()
    return redirect(url_for('main.index'))

@bp.route('/My-Events')
def My_Events():
    events = db.session.query(Event).filter_by(user_id = current_user.id).all()
    return render_template('my_event.html',events = events )

@bp.route('/Edit<id>', methods = ['GET', 'POST'])
def edit(id):
    form = Create()
    event = db.session.query(Event).filter_by(id = id).first()
    if form.validate_on_submit():
        file_path=check_upload_file(form)
        event.name = form.name.data
        event.description = form.description.data
        event.long_description = form.long_description.data
        event.ticket_price = form.ticket_price.data
        event.organiser = form.organiser.data
        event.type = form.type.data
        event.street = form.street.data
        event.city = form.city.data
        event.state = form.state.data
        event.postcode = form.postcode.data
        event.image = file_path
        event.start_date = form.start_date.data
        event.end_date = form.end_date.data
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('create.html', form = form)

def check_upload_file(form):
  #get file data from form  
  fp=form.image.data
  filename=fp.filename
  #get the current path of the module file… store image file relative to this path  
  BASE_PATH=os.path.dirname(__file__)
  #upload file location – directory of this file/static/image
  upload_path=os.path.join(BASE_PATH,'static/img',secure_filename(filename))
  #store relative path in DB as image location in HTML is relative
  db_upload_path='/static/img/' + secure_filename(filename)
  #save the file and return the db upload path  
  fp.save(upload_path)
  return db_upload_path

website/templates/booking_history.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12 col-lg-12">
    <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12 pb-2">
            <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
                <a href="#"
                    class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                    <span class="fs-4">Booking History</span>
                </a>
                <hr>

                <ul>
                    <a1 href="#" class="nav-link link-dark">Dashboard</a1>
                    <a1 href="#" class="nav-link link-dark">Order Options</a1>
                    <a1 href="#" class="nav-link link-dark">Payment and Tax</a1>
                    <a1 href="#" class="nav-link link-dark">Refunds and Credits</a1>
                    <hr>
                    <a1 href="#" class="nav-link link-dark">Privacy Settings</a1>
                </ul>

            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 pb-2 pt-2">
            <div class="album pt-2 pb-4">
                <div class="container">
                    <h1>Booked Events</h1>
                    <hr class="m-2">
                    <br>
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
                        {% for event in events %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{{event.image}}" class="card-img-top" alt="..." width=100% height="225">

                                <div class="card-body">
                                    <h3>{{event.name}}</h3>
                                    <p class="card-text">{{event.description}}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{{url_for('main.details', id=event.id)}}" type="button"
                                                class="btn btn-sm btn-outline-secondary">View</a>
                                        </div>                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
{% endblock %}

website/templates/create.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">
        {{wtf.quick_form(form)}}
      </div>
    </div>
  </div>

{% endblock %}

website/templates/event_creation.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="col-md-12 col-lg-12">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12 pb-2">
                    <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
                        <a href="#"
                            class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                            <span class="fs-4">Create an Event</span>
                        </a>
                        <hr>
                        <ul class="nav nav-pills flex-column mb-auto">
                            <li class="nav-item pill-1">
                                <a href="#" class="nav-link active" aria-current="page">
                                    <svg class="bi me-2" width="16" height="16">
                                        <use xlink:href="#checkcircle" />
                                    </svg>
                                    Basic Information
                                </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link link-dark">
                                    <svg class="bi me-2" width="16" height="16">
                                        <use xlink:href="#circle" />
                                    </svg>
                                    Additional Information
                                </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link link-dark">
                                    <svg class="bi me-2" width="16" height="16">
                                        <use xlink:href="#circle" />
                                    </svg>
                                    Ticketing
                                </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link link-dark">
                                    <svg class="bi me-2" width="16" height="16">
                                        <use xlink:href="#circle" />
                                    </svg>
                                    Confirmation
                                </a>
                            </li>

                        </ul>
                        <hr>

                        <ul>
                            <a1 href="#" class="nav-link link-dark">Dashboard</a1>
                            <a1 href="#" class="nav-link link-dark">Order Options</a1>
                            <a1 href="#" class="nav-link link-dark">Payment and Tax</a1>
                            <a1 href="#" class="nav-link link-dark">Marketing</a1>
                            <a1 href="#" class="nav-link link-dark">Manage Attendees</a1>
                            <a1 href="#" class="nav-link link-dark">Reports</a1>
                            <hr>
                            <a1 href="#" class="nav-link link-dark">Privacy Settings</a1>
                        </ul>

                    </div>
                </div>
                <form method="POST">
                <div class="col-lg-9 col-md-9 col-sm-12 pb-2 pt-2">
                    <div class="card rounded shadow p-3">
                        <h1>Basic Information
                        </h1>
                        <hr class="m-2">
                        <div class="col-sm-12 col-lg-12 pb-4 px-4">
                            <label for="ControlInput1">Event Name</label>
                            {{form.name (class="form-control", id="ControlInput1",
                            placeholder="Clear and Descriptive" )}}
                            <br>

                            <label for="ControlInput1">Organiser</label>
                            {{form.organiser (class="form-control", id="ControlInput1",
                            placeholder="Tell the attendees who organised this event" )}}   

                            <br>

                            <label for="ControlSelect1">Type</label>
                            {{form.type (class="form-control", id="ControlInput1",
                            placeholder="Select" )}}
                        </div>
                    </div>
                    

                    <div class="row">
                        <div class="col-8 col-sm-12 col-md-12 col-lg-6">
                            <div class="card rounded shadow mt-4 p-3">
                                <h1>Location</h1>
                                <p3>Help people in the area discover your event and let attendees know where to show up.
                                </p3>
                                <hr class="m-2">
                                <div class="col-sm-12 col-lg-12 pb-4 px-4">
                                    <label for="ControlInput1">Enter Address</label>
                                    {{form.street (class="form-control me-2 mb-3", id="ControlInput1",
                                    placeholder="Street" )}}
                                    {{form.city (class="form-control me-2 mb-3", id="ControlInput1",
                                    placeholder="City" )}}
                                    {{form.state (class="form-control me-2 mb-3", id="ControlInput1",
                                    placeholder="State" )}}
                                    {{form.postcode (class="form-control me-2 mb-3", id="ControlInput1",
                                    placeholder="Postcode" )}}
                                </div>

                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                            <div class="card rounded shadow mt-4 p-3">

                                <h1>Date and Time</h1>
                                <p3>Tell event-goers when your event starts and ends so they can make plans to attend.
                                </p3>
                                <hr class="m-2">

                                <div class="col-sm-12 col-lg-12 pt-2 pb-4 px-4">
                                    <label for="ControlInput1">Start Date/Time:</label>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <label for="ControlInput1" class="$-4">End Date/Time:</label>
                                    <br>
                                    <br>
                                    <br>
                                    <br>



                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="card rounded shadow mt-4 p-3">
                            <h1>Event Image</h1>
                            <p3>Tell event-goers when your event starts and ends so they can make plans to attend.</p3>
                            <hr class="m-2">
                            {{form.image}}

                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="card rounded shadow mt-4 p-3">
                            <h1>Description</h1>
                            <hr class="m-2">
                            <div class="col-sm-12 col-lg-12 pb-4 px-4">
                                <label for="exampleFormControlTextarea1">Description of Event</label>
                                {{form.description (class="form-control", id="exampleFormControlTextarea1",
                                rows = "3" )}}
                            </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-lg-3 col-md-2 offset-md-10 pt-3">
                        {{form.submit (class="btn btn-primary",id="submit",rows="3",value="Save Event" )}}
                    </div>
                </div>
            </form>
            </div>
        </div>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{First.image}}" class="center" alt="Responsive image"
                            style="width: 1200px; height: 337px; object-fit: cover;">
                    </div>
                    {% for carosel in carosels %}
                    <div class="carousel-item">
                        <img src="{{carosel.image}}" class="center" alt="Responsive image"
                            style="width: 1200px; height: 337px; object-fit: cover;">
                    </div>
                    {% endfor %}
                </div>

                <!-- Carousel Buttons -->

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>

            <!-- Start Carousel Body Text -->

            <div class="container maintext">
                <div class="row">
                    <div class="col-md-12 col-lg-12 pt-3 px-5">
                        <p class="maintext">Feed Me is a global self-service ticketing platform for live
                            experiences that allows anyone to create, share, find and attend events that fuel their
                            passions and enrich their lives. Our mission is
                            to bring the world together through live experiences.
                        </p>
                    </div>
                </div>
            </div>

            <!-- Header for Events on now -->
            <div class="row ">
                <div class="col-md-6 cold-lg-6">
                    <h3 class="pb-0.1 mb-0.4 ">
                        Events
                    </h3>
                </div>
            </div>


            <!-- Links -->

            <ul class="nav nav-pills border-bottom border-dark pb-1 pt-2">
                <li class="nav-item pill-1">
                    <a class="nav-link active" href="/">All</a>
                </li>
                <li class="nav-item pill-2">
                    <a class="nav-link" href="{{url_for('main.upcoming')}}">Upcoming</a>
                </li>
                <li class="nav-item pill-3">
                    <a class="nav-link" href="{{url_for('main.passed')}}">Ongoing</a>
                </li>
                <li class="nav-item pill-4">
                    <a class="nav-link" href="{{url_for('main.week')}}" tabindex="-1" aria-="true">This Week</a>
                </li>
            </ul>

            <div class="album pt-2 pb-4">
                <div class="container maintext">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        {% for event in events %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{{event.image}}" class="card-img-top" alt="Responsive image" 
                                style="width:100%; height: 225px; object-fit: cover; ">

                                <div class="card-body">
                                    <h3>{{event.name}}</h3>
                                    <p2>{{event.start_date}}</p2>
                                    <br>
                                    {% if event.start_date >= current %}
                                    <p3>Upcoming</p3>
                                    {% elif event.end_date >= current %}
                                    <p3>Ongoing</p3>
                                    {% else %}
                                    <p3>Passed</p3>
                                    {% endif %}
                                    <br>
                                    <p1>{{event.description}}
                                    </p1>
                                    <div class="d-flex justify-content-between align-items-center pt-2" alt="Responsive image">
                                        <div class="btn-group">
                                            <a  href="{{url_for('main.details', id=event.id)}}"type="button"
                                                class="btn btn-sm btn-outline-secondary">View</a>
                                                {% if current_user.is_authenticated %}
                                                <a  href="{{url_for('main.book', id=event.id)}}"type="button"
                                                class="btn btn-sm btn-outline-secondary">Book</a>
                                                {% else %}
                                                <a  href="{{url_for('auth.login')}}"type="button"
                                                class="btn btn-sm btn-outline-secondary">Book</a>
                                                {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">
          <h1>Please Login Here</h1>
        {{wtf.quick_form(form)}}
      </div>
    </div>
  </div>

{% endblock %}

website/templates/my_event.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12 col-lg-12">
    <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 col-12 pb-2">
            <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
                <a href="#"
                    class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                    <span class="fs-4">Events</span>
                </a>
                <hr>

                <ul>
                    <a1 href="#" class="nav-link link-dark">Dashboard</a1>
                    <a1 href="#" class="nav-link link-dark">Order Options</a1>
                    <a1 href="#" class="nav-link link-dark">Payment and Tax</a1>
                    <a1 href="#" class="nav-link link-dark">Refunds and Credits</a1>
                    <hr>
                    <a1 href="#" class="nav-link link-dark">Privacy Settings</a1>
                </ul>

            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 pb-2 pt-2">
            <div class="album pt-2 pb-4">
                <div class="container">
                    <h1>My Events</h1>
                    <hr class="m-2">
                    <br>
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
                        {% for event in events %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{{event.image}}" class="card-img-top" alt="..." width=100% height="225">

                                <div class="card-body">
                                    <h3>{{event.name}}</h3>
                                    <p class="card-text">{{event.description}}
                                    </p>
                                    <div class="btn-group">
                                        <a  href="{{url_for('main.details', id=event.id)}}"type="button"
                                            class="btn btn-sm btn-outline-secondary">View</a>
                                            <a  href="{{url_for('main.edit', id = event.id)}}"type="button"
                                            class="btn btn-sm btn-outline-secondary">Edit</a>
                                    </div>                                  </div>
                                        
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">
          <h1>Please Register Here</h1>
        {{wtf.quick_form(registerForm)}}
      </div>
    </div>
  </div>

{% endblock %}

website/templates/user.html
{% include "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div class="page-header">
    <h4>{{heading}}</h4>
</div>



<div class="container-fluid">
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

</div>



<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
{{ wtf.quick_form(form) }}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}